<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Author',
                'edit' => 1,
                'field' => 'author_id',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Category',
                'edit' => 1,
                'field' => 'category_id',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 4,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            4 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'excerpt',
                'edit' => 1,
                'field' => 'excerpt',
                'id' => 5,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            5 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Body',
                'edit' => 1,
                'field' => 'body',
                'id' => 6,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            6 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'display_name' => 'Post Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 7,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_description',
                'edit' => 1,
                'field' => 'meta_description',
                'id' => 9,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_keywords',
                'edit' => 1,
                'field' => 'meta_keywords',
                'id' => 10,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            10 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'display_name' => 'status',
                'edit' => 1,
                'field' => 'status',
                'id' => 11,
                'order' => 11,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 12,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            12 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 13,
                'order' => 13,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 14,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'author_id',
                'edit' => 0,
                'field' => 'author_id',
                'id' => 15,
                'order' => 2,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            15 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'title',
                'edit' => 1,
                'field' => 'title',
                'id' => 16,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'excerpt',
                'edit' => 1,
                'field' => 'excerpt',
                'id' => 17,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            17 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'body',
                'edit' => 1,
                'field' => 'body',
                'id' => 18,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            18 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title"}}',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 19,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_description',
                'edit' => 1,
                'field' => 'meta_description',
                'id' => 20,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'meta_keywords',
                'edit' => 1,
                'field' => 'meta_keywords',
                'id' => 21,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'display_name' => 'status',
                'edit' => 1,
                'field' => 'status',
                'id' => 22,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 23,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            23 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 24,
                'order' => 11,
                'read' => 0,
                'required' => 1,
                'type' => 'timestamp',
            ),
            24 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => '',
                'display_name' => 'image',
                'edit' => 1,
                'field' => 'image',
                'id' => 25,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 26,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            26 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'name',
                'edit' => 1,
                'field' => 'name',
                'id' => 27,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            27 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'email',
                'edit' => 1,
                'field' => 'email',
                'id' => 28,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'password',
                'edit' => 1,
                'field' => 'password',
                'id' => 29,
                'order' => 5,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            29 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"role_id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"on"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 30,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            30 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'remember_token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 31,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 32,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            32 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 33,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 34,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 35,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            35 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '',
                'display_name' => 'name',
                'edit' => 1,
                'field' => 'name',
                'id' => 36,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 37,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            37 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 38,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 39,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"default":1}',
                'display_name' => 'order',
                'edit' => 1,
                'field' => 'order',
                'id' => 41,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'name',
                'edit' => 1,
                'field' => 'name',
                'id' => 42,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name"}}',
                'display_name' => 'slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 43,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            42 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 44,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            43 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 45,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            44 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'id',
                'edit' => 0,
                'field' => 'id',
                'id' => 46,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 47,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'created_at',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 48,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            47 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '',
                'display_name' => 'updated_at',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 49,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '',
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 50,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'seo_title',
                'edit' => 1,
                'field' => 'seo_title',
                'id' => 51,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            50 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '',
                'display_name' => 'featured',
                'edit' => 1,
                'field' => 'featured',
                'id' => 52,
                'order' => 15,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            51 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'role_id',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 53,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            52 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Username',
                'edit' => 1,
                'field' => 'username',
                'id' => 54,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            53 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 55,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            54 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 56,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            55 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Description (max 250 characters)',
                'edit' => 1,
                'field' => 'description',
                'id' => 57,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Body',
                'edit' => 1,
                'field' => 'body',
                'id' => 58,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            57 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 59,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            58 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 60,
                'order' => 6,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Settings',
                'edit' => 1,
                'field' => 'settings',
                'id' => 61,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'hidden',
            ),
            60 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 62,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            61 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '',
                'display_name' => 'Locale',
                'edit' => 1,
                'field' => 'locale',
                'id' => 63,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            62 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 64,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Name (Basic, Standard, Premium, etc)',
                'edit' => 1,
                'field' => 'name',
                'id' => 65,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Description (optional)',
                'edit' => 1,
                'field' => 'description',
                'id' => 66,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            65 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Features (comma separated)',
                'edit' => 1,
                'field' => 'features',
                'id' => 67,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            66 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Role Id',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 69,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            67 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 70,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            68 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 71,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"announcement_user","pivot":"0","taggable":"0"}',
            'display_name' => 'Role (role permissions for this plan)',
                'edit' => 1,
                'field' => 'plan_belongsto_role_relationship',
                'id' => 72,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            70 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Default (Make this the default plan)',
                'edit' => 1,
                'field' => 'default',
                'id' => 73,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Price (for display purposes only)',
                'edit' => 1,
                'field' => 'price',
                'id' => 74,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Plan Id',
                'edit' => 1,
                'field' => 'plan_id',
                'id' => 75,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            73 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => NULL,
            'display_name' => 'Trial Days (If none, set to 0)',
                'edit' => 1,
                'field' => 'trial_days',
                'id' => 76,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            74 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 122,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            75 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Author Id',
                'edit' => 1,
                'field' => 'author_id',
                'id' => 123,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            76 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Title',
                'edit' => 1,
                'field' => 'title',
                'id' => 125,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            77 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Seo Title',
                'edit' => 1,
                'field' => 'seo_title',
                'id' => 126,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            78 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Excerpt',
                'edit' => 1,
                'field' => 'excerpt',
                'id' => 127,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            79 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Body',
                'edit' => 1,
                'field' => 'body',
                'id' => 128,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'rich_text_box',
            ),
            80 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"max":1,"min":1,"expanded":true,"show_folders":true,"show_toolbar":true,"allow_upload":true,"allow_move":false,"allow_delete":false,"allow_create_folder":false,"allow_rename":false,"allow_crop":true,"allowed":["image\\/jpeg","image\\/png"],"show_as_images":true,"hide_thumbnails":false,"quality":90}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 129,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'media_picker',
            ),
            81 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'display_name' => 'Slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 130,
                'order' => 10,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            82 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Meta Description',
                'edit' => 1,
                'field' => 'meta_description',
                'id' => 131,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            83 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Meta Keywords',
                'edit' => 1,
                'field' => 'meta_keywords',
                'id' => 132,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            84 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'display_name' => 'Status',
                'edit' => 1,
                'field' => 'status',
                'id' => 133,
                'order' => 15,
                'read' => 1,
                'required' => 1,
                'type' => 'select_dropdown',
            ),
            85 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Featured',
                'edit' => 1,
                'field' => 'featured',
                'id' => 134,
                'order' => 16,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            86 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 135,
                'order' => 17,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            87 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 136,
                'order' => 18,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            88 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"foreign_pivot_key":"actie_id","related_pivot_key":"category_id","parent_key":"id","model":"Wave\\\\Category","table":"categories","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"actie_category","pivot":"1","taggable":"0"}',
                'display_name' => 'categories',
                'edit' => 1,
                'field' => 'acty_hasmany_category_relationship',
                'id' => 137,
                'order' => 19,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            89 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Time Start',
                'edit' => 1,
                'field' => 'time_start',
                'id' => 139,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            90 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Time End',
                'edit' => 1,
                'field' => 'time_end',
                'id' => 140,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            91 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Location Human',
                'edit' => 1,
                'field' => 'location_human',
                'id' => 142,
                'order' => 12,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            92 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Location',
                'edit' => 1,
                'field' => 'location',
                'id' => 145,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'coordinates',
            ),
            93 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 146,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            94 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{"default":1}',
                'display_name' => 'Order',
                'edit' => 1,
                'field' => 'order',
                'id' => 147,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            95 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 148,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            96 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name"}}',
                'display_name' => 'Slug',
                'edit' => 1,
                'field' => 'slug',
                'id' => 149,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            97 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Color',
                'edit' => 1,
                'field' => 'color',
                'id' => 150,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            98 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 12,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 151,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            99 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 12,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 152,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            100 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 9,
                'delete' => 1,
                'details' => '{"foreign_pivot_key":"actie_id","related_pivot_key":"actie_theme_id","parent_key":"id","model":"Wave\\\\ActieTheme","table":"actie_themes","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"actie_actie_theme","pivot":"1","taggable":"0"}',
                'display_name' => 'themes',
                'edit' => 1,
                'field' => 'acty_hasmany_actie_theme_relationship',
                'id' => 153,
                'order' => 19,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
        ));
        
        
    }
}