<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 372,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 373,
                'data_type_id' => 1,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Author',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 374,
                'data_type_id' => 1,
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 375,
                'data_type_id' => 1,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 376,
                'data_type_id' => 1,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Excerpt',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 377,
                'data_type_id' => 1,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 378,
                'data_type_id' => 1,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Post Image',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 379,
                'data_type_id' => 1,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 380,
                'data_type_id' => 1,
                'field' => 'meta_description',
                'type' => 'text_area',
                'display_name' => 'meta_description',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            9 => 
            array (
                'id' => 381,
                'data_type_id' => 1,
                'field' => 'meta_keywords',
                'type' => 'text_area',
                'display_name' => 'meta_keywords',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 10,
            ),
            10 => 
            array (
                'id' => 382,
                'data_type_id' => 1,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order' => 11,
            ),
            11 => 
            array (
                'id' => 383,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 12,
            ),
            12 => 
            array (
                'id' => 384,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 13,
            ),
            13 => 
            array (
                'id' => 385,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            14 => 
            array (
                'id' => 386,
                'data_type_id' => 2,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'author_id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            15 => 
            array (
                'id' => 387,
                'data_type_id' => 2,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            16 => 
            array (
                'id' => 388,
                'data_type_id' => 2,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'excerpt',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            17 => 
            array (
                'id' => 389,
                'data_type_id' => 2,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'body',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"tinymceOptions":{"inline_styles":false,"plugins":"link, image, code, table, textcolor, lists, paste","paste_remove_styles":true,"theme_advanced_buttons3_add":"pastetext,pasteword,selectall", "toolbar": "styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table | code | removeformat"}}',
                'order' => 5,
            ),
            18 => 
            array (
                'id' => 390,
                'data_type_id' => 2,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title"}}',
                'order' => 6,
            ),
            19 => 
            array (
                'id' => 391,
                'data_type_id' => 2,
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'meta_description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            20 => 
            array (
                'id' => 392,
                'data_type_id' => 2,
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'meta_keywords',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            21 => 
            array (
                'id' => 393,
                'data_type_id' => 2,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'order' => 9,
            ),
            22 => 
            array (
                'id' => 394,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            23 => 
            array (
                'id' => 395,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            24 => 
            array (
                'id' => 396,
                'data_type_id' => 2,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'image',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            25 => 
            array (
                'id' => 397,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            26 => 
            array (
                'id' => 398,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            27 => 
            array (
                'id' => 399,
                'data_type_id' => 3,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            28 => 
            array (
                'id' => 400,
                'data_type_id' => 3,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            29 => 
            array (
                'id' => 401,
                'data_type_id' => 3,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Additional Roles',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"role_id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"on"}',
                'order' => 11,
            ),
            30 => 
            array (
                'id' => 402,
                'data_type_id' => 3,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'remember_token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            31 => 
            array (
                'id' => 403,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            32 => 
            array (
                'id' => 404,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            33 => 
            array (
                'id' => 405,
                'data_type_id' => 3,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'avatar',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            34 => 
            array (
                'id' => 406,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            35 => 
            array (
                'id' => 407,
                'data_type_id' => 5,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            36 => 
            array (
                'id' => 408,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            37 => 
            array (
                'id' => 409,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            38 => 
            array (
                'id' => 410,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            39 => 
            array (
                'id' => 411,
                'data_type_id' => 4,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            40 => 
            array (
                'id' => 412,
                'data_type_id' => 4,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name"},"validation":{"rule":"required|unique:categories"}}',
                'order' => 5,
            ),
            41 => 
            array (
                'id' => 413,
                'data_type_id' => 4,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            42 => 
            array (
                'id' => 414,
                'data_type_id' => 4,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            43 => 
            array (
                'id' => 415,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            44 => 
            array (
                'id' => 416,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            45 => 
            array (
                'id' => 417,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            46 => 
            array (
                'id' => 418,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            47 => 
            array (
                'id' => 419,
                'data_type_id' => 6,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            48 => 
            array (
                'id' => 420,
                'data_type_id' => 1,
                'field' => 'seo_title',
                'type' => 'text',
                'display_name' => 'seo_title',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 14,
            ),
            49 => 
            array (
                'id' => 421,
                'data_type_id' => 1,
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'featured',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 15,
            ),
            50 => 
            array (
                'id' => 422,
                'data_type_id' => 3,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            51 => 
            array (
                'id' => 423,
                'data_type_id' => 3,
                'field' => 'username',
                'type' => 'text',
                'display_name' => 'Username',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            52 => 
            array (
                'id' => 424,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            53 => 
            array (
                'id' => 425,
                'data_type_id' => 7,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            54 => 
            array (
                'id' => 426,
                'data_type_id' => 7,
                'field' => 'description',
                'type' => 'text_area',
            'display_name' => 'Description (max 250 characters)',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            55 => 
            array (
                'id' => 427,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            56 => 
            array (
                'id' => 428,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            57 => 
            array (
                'id' => 429,
                'data_type_id' => 3,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            58 => 
            array (
                'id' => 430,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 431,
                'data_type_id' => 9,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 432,
                'data_type_id' => 9,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 3,
            ),
            61 => 
            array (
                'id' => 433,
                'data_type_id' => 9,
                'field' => 'excerpt',
                'type' => 'text',
                'display_name' => 'Excerpt',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 5,
            ),
            62 => 
            array (
                'id' => 434,
                'data_type_id' => 9,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"},"tinymceOptions":{"inline_styles":false,"plugins":"link, image, code, table, textcolor, lists","paste_remove_styles":true,"theme_advanced_buttons3_add":"pastetext,pasteword,selectall","toolbar":"blocks | bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table | code | removeformat"}}',
                'order' => 6,
            ),
            63 => 
            array (
                'id' => 435,
                'data_type_id' => 9,
                'field' => 'image',
                'type' => 'media_picker',
                'display_name' => 'Afbeelding',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"max":1,"min":0,"expanded":true,"show_folders":true,"show_toolbar":true,"allow_upload":true,"allow_move":false,"allow_delete":false,"allow_create_folder":false,"allow_rename":false,"allow_crop":true,"allowed":["image\\/jpeg","image\\/png"],"show_as_images":true,"hide_thumbnails":false,"quality":70,"upsize":true,"thumbnails":[{"type":"resize","name":"resize-500","width":"500"}],"foreign_key_name":"actie_id"}',
                'order' => 9,
            ),
            64 => 
            array (
                'id' => 436,
                'data_type_id' => 9,
                'field' => 'slug',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title"},"validation":{"rule":"required|unique:acties"}}',
                'order' => 10,
            ),
            65 => 
            array (
                'id' => 437,
                'data_type_id' => 9,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Pageviews',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order' => 15,
            ),
            66 => 
            array (
                'id' => 438,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'GeÃ¼pdatet op',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 17,
            ),
            67 => 
            array (
                'id' => 439,
                'data_type_id' => 9,
                'field' => 'acty_hasmany_category_relationship',
                'type' => 'relationship',
                'display_name' => 'CategoriÃ«n',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"foreign_pivot_key":"actie_id","related_pivot_key":"category_id","parent_key":"id","model":"App\\\\Models\\\\Category","table":"categories","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"actie_category","pivot":"1","taggable":"on"}',
                'order' => 19,
            ),
            68 => 
            array (
                'id' => 440,
                'data_type_id' => 9,
                'field' => 'time_start',
                'type' => 'timestamp',
                'display_name' => 'Starttijd',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            69 => 
            array (
                'id' => 441,
                'data_type_id' => 9,
                'field' => 'time_end',
                'type' => 'timestamp',
                'display_name' => 'Eindtijd',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            70 => 
            array (
                'id' => 442,
                'data_type_id' => 9,
                'field' => 'location_human',
                'type' => 'text',
            'display_name' => 'Locatie (tekst)',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            71 => 
            array (
                'id' => 443,
                'data_type_id' => 9,
                'field' => 'location',
                'type' => 'coordinates',
                'display_name' => 'Locatie',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            72 => 
            array (
                'id' => 444,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            73 => 
            array (
                'id' => 445,
                'data_type_id' => 12,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            74 => 
            array (
                'id' => 446,
                'data_type_id' => 12,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name","forceUpdate":true},"validation":{"rule":"required|unique:themes"}}',
                'order' => 4,
            ),
            75 => 
            array (
                'id' => 447,
                'data_type_id' => 12,
                'field' => 'color',
                'type' => 'color',
                'display_name' => 'Color',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            76 => 
            array (
                'id' => 448,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            77 => 
            array (
                'id' => 449,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            78 => 
            array (
                'id' => 450,
                'data_type_id' => 9,
                'field' => 'acty_hasmany_actie_theme_relationship',
                'type' => 'relationship',
                'display_name' => 'Thema\'s',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"foreign_pivot_key":"actie_id","related_pivot_key":"theme_id","parent_key":"id","model":"App\\\\Models\\\\Theme","table":"themes","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"actie_theme","pivot":"1","taggable":"on"}',
                'order' => 19,
            ),
            79 => 
            array (
                'id' => 451,
                'data_type_id' => 9,
                'field' => 'externe_link',
                'type' => 'text',
                'display_name' => 'Externe Link',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|url"}}',
                'order' => 7,
            ),
            80 => 
            array (
                'id' => 452,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            81 => 
            array (
                'id' => 453,
                'data_type_id' => 14,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            82 => 
            array (
                'id' => 454,
                'data_type_id' => 14,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            83 => 
            array (
                'id' => 455,
                'data_type_id' => 14,
                'field' => 'website',
                'type' => 'text',
                'display_name' => 'Website',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"url"}}',
                'order' => 4,
            ),
            84 => 
            array (
                'id' => 456,
                'data_type_id' => 14,
                'field' => 'logo',
                'type' => 'media_picker',
                'display_name' => 'Logo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"max":1,"min":1,"expanded":true,"show_folders":true,"show_toolbar":true,"allow_upload":true,"allow_move":false,"allow_delete":false,"allow_create_folder":false,"allow_rename":false,"allow_crop":true,"allowed":["image\\/jpeg","image\\/png"],"show_as_images":true,"hide_thumbnails":false,"quality":70,"upsize":true,"thumbnails":[{"type":"resize","name":"resize-500","width":"500"}],"foreign_key_name":"organizer_id"}',
                'order' => 5,
            ),
            85 => 
            array (
                'id' => 457,
                'data_type_id' => 14,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Created At',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name","forceUpdate":true},"validation":{"rule":"required|unique:organizers"}}',
                'order' => 6,
            ),
            86 => 
            array (
                'id' => 458,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            87 => 
            array (
                'id' => 459,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            88 => 
            array (
                'id' => 460,
                'data_type_id' => 9,
                'field' => 'acty_belongstomany_organizer_relationship',
                'type' => 'relationship',
                'display_name' => 'Organisatoren',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Organizer","table":"organizers","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"actie_organizer","pivot":"1","taggable":"0"}',
                'order' => 20,
            ),
            89 => 
            array (
                'id' => 461,
                'data_type_id' => 21,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            90 => 
            array (
                'id' => 462,
                'data_type_id' => 21,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User ID',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            91 => 
            array (
                'id' => 463,
                'data_type_id' => 21,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            92 => 
            array (
                'id' => 464,
                'data_type_id' => 21,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            93 => 
            array (
                'id' => 465,
                'data_type_id' => 21,
                'field' => 'externe_link',
                'type' => 'text',
                'display_name' => 'Externe Link',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"url"}}',
                'order' => 5,
            ),
            94 => 
            array (
                'id' => 466,
                'data_type_id' => 21,
                'field' => 'time_start',
                'type' => 'timestamp',
                'display_name' => 'Time Start',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            95 => 
            array (
                'id' => 467,
                'data_type_id' => 21,
                'field' => 'time_end',
                'type' => 'timestamp',
                'display_name' => 'Time End',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            96 => 
            array (
                'id' => 468,
                'data_type_id' => 21,
                'field' => 'location',
                'type' => 'text',
                'display_name' => 'Location',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            97 => 
            array (
                'id' => 469,
                'data_type_id' => 21,
                'field' => 'location_human',
                'type' => 'text',
                'display_name' => 'Location Human',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            98 => 
            array (
                'id' => 470,
                'data_type_id' => 21,
                'field' => 'image',
                'type' => 'text',
                'display_name' => 'Image',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            99 => 
            array (
                'id' => 471,
                'data_type_id' => 21,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"PENDING","options":{"PENDING":"pending","APPROVED":"approved","REJECTED":"rejected"}}',
                'order' => 11,
            ),
            100 => 
            array (
                'id' => 472,
                'data_type_id' => 21,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            101 => 
            array (
                'id' => 473,
                'data_type_id' => 21,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            102 => 
            array (
                'id' => 474,
                'data_type_id' => 21,
                'field' => 'reports_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"reports","pivot":"0","taggable":"0"}',
                'order' => 14,
            ),
            103 => 
            array (
                'id' => 475,
                'data_type_id' => 21,
                'field' => 'organizer_ids',
                'type' => 'text',
                'display_name' => 'Organizer Ids',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            104 => 
            array (
                'id' => 476,
                'data_type_id' => 3,
                'field' => 'verified',
                'type' => 'checkbox',
                'display_name' => 'Verified',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Verified","off":"Not Verified","checked":false}',
                'order' => 8,
            ),
            105 => 
            array (
                'id' => 477,
                'data_type_id' => 3,
                'field' => 'verification_code',
                'type' => 'text',
                'display_name' => 'Verification Code',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            106 => 
            array (
                'id' => 478,
                'data_type_id' => 3,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            107 => 
            array (
                'id' => 479,
                'data_type_id' => 14,
                'field' => 'organizer_belongstomany_theme_relationship',
                'type' => 'relationship',
                'display_name' => 'Themes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Theme","table":"themes","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"organizer_theme","pivot":"1","taggable":"0"}',
                'order' => 9,
            ),
            108 => 
            array (
                'id' => 480,
                'data_type_id' => 9,
                'field' => 'keywords',
                'type' => 'text',
                'display_name' => 'Keywords',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required"}}',
                'order' => 6,
            ),
            109 => 
            array (
                'id' => 481,
                'data_type_id' => 22,
                'field' => 'key',
                'type' => 'text',
                'display_name' => 'Key',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            110 => 
            array (
                'id' => 482,
                'data_type_id' => 22,
                'field' => 'path',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            111 => 
            array (
                'id' => 483,
                'data_type_id' => 22,
                'field' => 'user_id',
                'type' => 'number',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 1,
            ),
            112 => 
            array (
                'id' => 484,
                'data_type_id' => 22,
                'field' => 'organizer_id',
                'type' => 'number',
                'display_name' => 'Organizer Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            113 => 
            array (
                'id' => 485,
                'data_type_id' => 22,
                'field' => 'actie_id',
                'type' => 'number',
                'display_name' => 'Actie Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            114 => 
            array (
                'id' => 486,
                'data_type_id' => 22,
                'field' => 'report_id',
                'type' => 'number',
                'display_name' => 'Report Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            115 => 
            array (
                'id' => 487,
                'data_type_id' => 22,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            116 => 
            array (
                'id' => 488,
                'data_type_id' => 22,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            117 => 
            array (
                'id' => 489,
                'data_type_id' => 22,
                'field' => 'size',
                'type' => 'number',
                'display_name' => 'Size',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            118 => 
            array (
                'id' => 490,
                'data_type_id' => 14,
                'field' => 'user_id',
                'type' => 'hidden',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            119 => 
            array (
                'id' => 491,
                'data_type_id' => 9,
                'field' => 'pageviews',
                'type' => 'text',
                'display_name' => 'Gemaakt op',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            120 => 
            array (
                'id' => 492,
                'data_type_id' => 14,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Emailadres',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"email"}}',
                'order' => 7,
            ),
            121 => 
            array (
                'id' => 493,
                'data_type_id' => 25,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            122 => 
            array (
                'id' => 494,
                'data_type_id' => 25,
                'field' => 'question',
                'type' => 'text',
                'display_name' => 'Question',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            123 => 
            array (
                'id' => 495,
                'data_type_id' => 25,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            124 => 
            array (
                'id' => 496,
                'data_type_id' => 25,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            125 => 
            array (
                'id' => 497,
                'data_type_id' => 26,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            126 => 
            array (
                'id' => 498,
                'data_type_id' => 26,
                'field' => 'answer',
                'type' => 'text',
                'display_name' => 'Answer',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            127 => 
            array (
                'id' => 499,
                'data_type_id' => 26,
                'field' => 'question_id',
                'type' => 'number',
                'display_name' => 'Question Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            128 => 
            array (
                'id' => 500,
                'data_type_id' => 26,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            129 => 
            array (
                'id' => 501,
                'data_type_id' => 26,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            130 => 
            array (
                'id' => 502,
                'data_type_id' => 9,
                'field' => 'disobedient',
                'type' => 'checkbox',
                'display_name' => 'Slug',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 13,
            ),
            131 => 
            array (
                'id' => 503,
                'data_type_id' => 26,
                'field' => 'answer_belongsto_question_relationship',
                'type' => 'relationship',
                'display_name' => 'Question',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Question","table":"questions","type":"belongsTo","column":"question_id","key":"id","label":"question","pivot_table":"actie_category","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            132 => 
            array (
                'id' => 504,
                'data_type_id' => 27,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            133 => 
            array (
                'id' => 505,
                'data_type_id' => 27,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            134 => 
            array (
                'id' => 506,
                'data_type_id' => 27,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            135 => 
            array (
                'id' => 507,
                'data_type_id' => 27,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            136 => 
            array (
                'id' => 508,
                'data_type_id' => 27,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            137 => 
            array (
                'id' => 509,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            138 => 
            array (
                'id' => 510,
                'data_type_id' => 25,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"ACTIVE","options":{"ACTIVE":"ACTIVE","INACTIVE":"INACTIVE"}}',
                'order' => 5,
            ),
            139 => 
            array (
                'id' => 511,
                'data_type_id' => 25,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            140 => 
            array (
                'id' => 512,
                'data_type_id' => 25,
                'field' => 'subject',
                'type' => 'text',
                'display_name' => 'Subject',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            141 => 
            array (
                'id' => 513,
                'data_type_id' => 7,
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            142 => 
            array (
                'id' => 514,
                'data_type_id' => 7,
                'field' => 'color',
                'type' => 'color',
                'display_name' => 'Color',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            143 => 
            array (
                'id' => 515,
                'data_type_id' => 7,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
        ));
        
        
    }
}