<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-news',
                'id' => 3,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.posts.index',
                'target' => '_self',
                'title' => 'Posts',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-person',
                'id' => 4,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 37,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-12-20 12:56:09',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-categories',
                'id' => 5,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 38,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-file-text',
                'id' => 6,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.pages.index',
                'target' => '_self',
                'title' => 'Pages',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-lock',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 37,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-12-20 12:56:14',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-tools',
                'id' => 8,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-list',
                'id' => 9,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-data',
                'id' => 10,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-compass',
                'id' => 11,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '/admin/compass',
            ),
            10 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-hook',
                'id' => 12,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => '',
                'parent_id' => 8,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2018-06-22 20:55:55',
                'url' => '/admin/hooks',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-settings',
                'id' => 13,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2021-12-20 12:58:31',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:31:00',
                'icon_class' => 'voyager-paint-bucket',
                'id' => 14,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Themes',
                'updated_at' => '2021-12-20 12:58:32',
                'url' => '/admin/themes',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 14:48:21',
                'icon_class' => 'home',
                'id' => 15,
                'menu_id' => 2,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'wave.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2018-03-23 16:25:44',
                'url' => '',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 14:49:36',
                'icon_class' => 'info',
                'id' => 16,
                'menu_id' => 2,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Resources',
                'updated_at' => '2017-11-28 15:11:13',
                'url' => '#_',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 14:56:58',
                'icon_class' => NULL,
                'id' => 19,
                'menu_id' => 2,
                'order' => 1,
                'parameters' => '',
                'parent_id' => 18,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Next Child',
                'updated_at' => '2017-11-28 14:57:10',
                'url' => '/next',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 14:57:07',
                'icon_class' => NULL,
                'id' => 20,
                'menu_id' => 2,
                'order' => 2,
                'parameters' => '',
                'parent_id' => 18,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Next Child 2',
                'updated_at' => '2017-11-28 14:57:12',
                'url' => '/next',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 15:08:56',
                'icon_class' => NULL,
                'id' => 21,
                'menu_id' => 2,
                'order' => 1,
                'parameters' => '',
                'parent_id' => 16,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Documentation',
                'updated_at' => '2017-11-28 15:09:14',
                'url' => '/docs',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 15:09:22',
                'icon_class' => NULL,
                'id' => 22,
                'menu_id' => 2,
                'order' => 2,
                'parameters' => '',
                'parent_id' => 16,
                'route' => NULL,
                'target' => '_blank',
                'title' => 'Videos',
                'updated_at' => '2017-11-28 15:09:25',
                'url' => 'https://devdojo.com/series/wave',
            ),
            19 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-28 15:09:56',
                'icon_class' => 'lifesaver',
                'id' => 23,
                'menu_id' => 2,
                'order' => 3,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_blank',
                'title' => 'Support',
                'updated_at' => '2018-03-31 18:22:05',
                'url' => 'https://devdojo.com/forums/category/wave',
            ),
            20 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-03-31 18:22:02',
                'icon_class' => NULL,
                'id' => 25,
                'menu_id' => 2,
                'order' => 3,
                'parameters' => '',
                'parent_id' => 16,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Blog',
                'updated_at' => '2018-03-31 18:22:08',
                'url' => '/blog',
            ),
            21 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-04-13 22:29:33',
                'icon_class' => NULL,
                'id' => 26,
                'menu_id' => 3,
                'order' => 99,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Home',
                'updated_at' => '2018-08-28 18:39:05',
                'url' => '/#',
            ),
            22 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-04-13 22:30:26',
                'icon_class' => NULL,
                'id' => 27,
                'menu_id' => 3,
                'order' => 100,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Features',
                'updated_at' => '2018-08-28 00:24:49',
                'url' => '/#features',
            ),
            23 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-04-13 22:31:03',
                'icon_class' => NULL,
                'id' => 28,
                'menu_id' => 3,
                'order' => 101,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Testimonials',
                'updated_at' => '2018-08-28 00:24:57',
                'url' => '/#testimonials',
            ),
            24 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-04-13 22:31:52',
                'icon_class' => NULL,
                'id' => 29,
                'menu_id' => 3,
                'order' => 102,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Pricing',
                'updated_at' => '2018-08-28 00:25:04',
                'url' => '/#pricing',
            ),
            25 => 
            array (
                'color' => NULL,
                'created_at' => '2018-05-20 21:08:14',
                'icon_class' => 'voyager-megaphone',
                'id' => 30,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Announcements',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '/admin/announcements',
            ),
            26 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-06-22 20:53:25',
                'icon_class' => 'voyager-bread',
                'id' => 31,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2018-06-22 20:54:13',
                'url' => '',
            ),
            27 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-08-24 19:41:14',
                'icon_class' => NULL,
                'id' => 33,
                'menu_id' => 3,
                'order' => 103,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'wave.blog',
                'target' => '_self',
                'title' => 'Blog',
                'updated_at' => '2018-08-24 19:41:14',
                'url' => '',
            ),
            28 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-11-24 16:23:01',
                'icon_class' => 'voyager-exclamation',
                'id' => 34,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 38,
                'route' => 'voyager.acties.index',
                'target' => '_self',
                'title' => 'Acties',
                'updated_at' => '2021-12-20 12:57:04',
                'url' => '',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-18 16:24:23',
                'icon_class' => NULL,
                'id' => 36,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 38,
                'route' => 'voyager.actie-themes.index',
                'target' => '_self',
                'title' => 'Actie Themes',
                'updated_at' => '2021-12-20 12:58:14',
                'url' => '',
            ),
            30 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-20 12:55:52',
                'icon_class' => NULL,
                'id' => 37,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Accounts',
                'updated_at' => '2021-12-20 12:57:06',
                'url' => '',
            ),
            31 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-20 12:56:41',
                'icon_class' => NULL,
                'id' => 38,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Acties & meer',
                'updated_at' => '2021-12-20 12:56:51',
                'url' => '',
            ),
        ));
        
        
    }
}