<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-news',
                'id' => 3,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.posts.index',
                'target' => '_self',
                'title' => 'Posts',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-person',
                'id' => 4,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 37,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-12-20 12:56:09',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-categories',
                'id' => 5,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 38,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categoriën',
                'updated_at' => '2022-02-02 14:16:09',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-file-text',
                'id' => 6,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.pages.index',
                'target' => '_self',
                'title' => 'Pagina\'s',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-lock',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 37,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-12-20 12:56:14',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-tools',
                'id' => 8,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-list',
                'id' => 9,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-data',
                'id' => 10,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-compass',
                'id' => 11,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2018-05-20 21:08:37',
                'url' => '/admin/compass',
            ),
            10 => 
            array (
                'color' => '#000000',
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-hook',
                'id' => 12,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => '',
                'parent_id' => 8,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2018-06-22 20:55:55',
                'url' => '/admin/hooks',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2017-11-21 16:23:22',
                'icon_class' => 'voyager-settings',
                'id' => 13,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2021-12-20 12:58:31',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2018-05-20 21:08:14',
                'icon_class' => 'voyager-megaphone',
                'id' => 30,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Announcements',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '/admin/announcements',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2018-06-22 20:53:25',
                'icon_class' => 'voyager-bread',
                'id' => 31,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 8,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2018-06-22 20:54:13',
                'url' => '',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-11-24 16:23:01',
                'icon_class' => 'voyager-exclamation',
                'id' => 34,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 38,
                'route' => 'voyager.acties.index',
                'target' => '_self',
                'title' => 'Acties',
                'updated_at' => '2022-01-19 15:49:14',
                'url' => '',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-20 12:55:52',
                'icon_class' => 'voyager-people',
                'id' => 37,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Accounts',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-20 12:56:41',
                'icon_class' => 'voyager-exclamation',
                'id' => 38,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Acties & Organisatoren',
                'updated_at' => '2022-01-03 15:53:16',
                'url' => '',
            ),
            17 => 
            array (
                'color' => NULL,
                'created_at' => '2022-01-03 15:53:00',
                'icon_class' => 'voyager-pirate',
                'id' => 39,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 38,
                'route' => 'voyager.organizers.index',
                'target' => '_self',
                'title' => 'Organisatoren',
                'updated_at' => '2022-01-19 15:49:14',
                'url' => '',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-19 15:46:35',
                'icon_class' => 'voyager-question',
                'id' => 44,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 38,
                'route' => 'voyager.reports.index',
                'target' => '_self',
                'title' => 'Reports',
                'updated_at' => '2022-02-21 10:47:02',
                'url' => '',
            ),
            19 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-02-02 14:15:54',
                'icon_class' => 'voyager-bubble-hear',
                'id' => 45,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 38,
                'route' => 'voyager.themes.index',
                'target' => '_self',
                'title' => 'Thema\'s',
                'updated_at' => '2022-02-02 14:16:09',
                'url' => '',
            ),
        ));
        
        
    }
}