/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actie: typeof import('./resources/views/assets/js/components/partials/Actie.vue')['default']
    ActieAgenda: typeof import('./resources/views/assets/js/components/apps/ActieAgenda.vue')['default']
    ActieForm: typeof import('./resources/views/assets/js/components/forms/ActieForm.vue')['default']
    ActieSmall: typeof import('./resources/views/assets/js/components/partials/ActieSmall.vue')['default']
    ActieWijzer: typeof import('./resources/views/assets/js/components/apps/ActieWijzer.vue')['default']
    AddActie: typeof import('./resources/views/assets/js/components/apps/AddActie.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Collapsible: typeof import('./resources/views/assets/js/components/partials/Collapsible.vue')['default']
    CopyTextField: typeof import('./resources/views/assets/js/components/partials/CopyTextField.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ForgotPassword: typeof import('./resources/views/assets/js/components/forms/ForgotPassword.vue')['default']
    FormAutocomplete: typeof import('./resources/views/assets/js/components/formfields/FormAutocomplete.vue')['default']
    FormField: typeof import('./resources/views/assets/js/components/formfields/FormField.vue')['default']
    FormImage: typeof import('./resources/views/assets/js/components/formfields/FormImage.vue')['default']
    FormSlider: typeof import('./resources/views/assets/js/components/formfields/FormSlider.vue')['default']
    FormUrls: typeof import('./resources/views/assets/js/components/formfields/FormUrls.vue')['default']
    HomeAgenda: typeof import('./resources/views/assets/js/components/apps/HomeAgenda.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./resources/views/assets/js/components/forms/Login.vue')['default']
    LoginOrRegister: typeof import('./resources/views/assets/js/components/apps/LoginOrRegister.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Newsletter: typeof import('./resources/views/assets/js/components/forms/Newsletter.vue')['default']
    Notifications: typeof import('./resources/views/assets/js/components/apps/Notifications.vue')['default']
    Organizer: typeof import('./resources/views/assets/js/components/partials/Organizer.vue')['default']
    OrganizerForm: typeof import('./resources/views/assets/js/components/forms/OrganizerForm.vue')['default']
    Organizers: typeof import('./resources/views/assets/js/components/apps/Organizers.vue')['default']
    OrganizersFeatured: typeof import('./resources/views/assets/js/components/apps/OrganizersFeatured.vue')['default']
    Pagination: typeof import('./resources/views/assets/js/components/partials/Pagination.vue')['default']
    Profile: typeof import('./resources/views/assets/js/components/forms/Profile.vue')['default']
    ProgressBar: typeof import('./resources/views/assets/js/components/partials/ProgressBar.vue')['default']
    Question: typeof import('./resources/views/assets/js/components/partials/Question.vue')['default']
    Referentie: typeof import('./resources/views/assets/js/components/partials/Referentie.vue')['default']
    Referenties: typeof import('./resources/views/assets/js/components/apps/Referenties.vue')['default']
    Register: typeof import('./resources/views/assets/js/components/forms/Register.vue')['default']
    ResetPassword: typeof import('./resources/views/assets/js/components/forms/ResetPassword.vue')['default']
    RichTextField: typeof import('./resources/views/assets/js/components/formfields/RichTextField.vue')['default']
    Security: typeof import('./resources/views/assets/js/components/forms/Security.vue')['default']
    SimpleMap: typeof import('./resources/views/assets/js/components/partials/SimpleMap.vue')['default']
    StepProgress: typeof import('./resources/views/assets/js/components/partials/StepProgress.vue')['default']
    SuccessBlock: typeof import('./resources/views/assets/js/components/partials/SuccessBlock.vue')['default']
    SuccessGIF: typeof import('./resources/views/assets/js/components/partials/SuccessGIF.vue')['default']
    ThemeQuestion: typeof import('./resources/views/assets/js/components/partials/ThemeQuestion.vue')['default']
    ThemesChips: typeof import('./resources/views/assets/js/components/partials/ThemesChips.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WidgetAgenda: typeof import('./resources/views/assets/js/components/apps/WidgetAgenda.vue')['default']
  }
}
