services:
  #PHP Service (app)
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: watkanikdoen/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_ENV: development
      CONTAINER_ROLE: app
    working_dir: /var/www
    ports: 
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - default
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: watkanikdoen_app
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_dbdata:/var/lib/mysql/
    networks:
      - default

#Docker Networks
networks:
  default:
    driver: bridge

#Volumes
volumes:
  mysql_dbdata:
    driver: local